
name: 'test_wk'

on:
  schedule:
    - cron: "35 16 */15 * *"
  # 点击star时触发运行
  #watch:
    #types: started
  # 手动触发
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
        
 #     - name: test
 #       env:
 #         workflow_name: ${{ github.workflow_ref }}
 #       run: |
 #         echo ${{ github.workflow_ref }}
 #         ls -a
 #         echo ${workflow_name%%@*}
 #         mkdir dists && cp -r ./.github ./dists
 #         ls -a . ./dists/.github
 #         workflow_name=$(echo "${workflow_name}" | sed 's/^[^/]*\/[^/]*\///;s/@.*$//')
 #         cat ${workflow_name}
      
      - name: Random Cron
        uses: grbnb/random-workflow-cron@v2
        with:
          #ref_branch: main
          #author: ${{ secrets.AUTHOR }}
          github_token: ${{ secrets.PAT }}
          #push_switch: false
          keep_history: true
          time_zone: "UTC+8"
          hour_start: 0
          hour_end: 21
          interval_count: 1
          cron_dmw: "*/15 * *"
          
      - name: run bash
        env:
          workflow_name: ${{ github.workflow_ref }}
        run: |
          echo ${{ github.workflow_ref }}
          ls -a
          echo ${workflow_name%%@*}
          mkdir dists && cp -r ./.github ./dists
          ls -a . ./dists/.github
          workflow_name=$(echo "${workflow_name}" | sed 's/^[^/]*\/[^/]*\///;s/@.*$//')
          cat ${workflow_name}
      
